-- PL/SQL 사용하여 한번에 여러 개의 SQL 구문 실행 

SET SERVEROUTPUT ON;

DECLARE 
    EMPLOYEE_LIST EMPLOYEES%ROWTYPE;
    DEPARTMENT_LIST DEPARTMENTS%ROWTYPE;
    JOB_LIST JOBS%ROWTYPE;
BEGIN
    -- SELECT 후 변수에 값 담기 
    SELECT * INTO EMPLOYEE_LIST FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;
    SELECT * INTO DEPARTMENT_LIST FROM DEPARTMENTS WHERE DEPARTMENT_ID = 10;
    SELECT * INTO JOB_LIST FROM JOBS WHERE JOB_ID = 'ST_CLERK';
    -- 출력 (SERVEROUTPUT)
    DBMS_OUTPUT.PUT_LINE(EMPLOYEE_LIST.LAST_NAME);
    DBMS_OUTPUT.PUT_LINE(DEPARTMENT_LIST.LOCATION_ID);
    DBMS_OUTPUT.PUT_LINE(JOB_LIST.JOB_ID);
END; 
/
-- 하나의 블록 실행 위해서는 역슬래쉬(/) 사용 필요

BEGIN
    UPDATE EMPLOYEES SET SALARY = SALARY * 1.1 WHERE EMPLOYEE_ID = 100;
    UPDATE EMPLOYEES SET COMMISSION_PCT = COMMISSION_PCT * 1.2 WHERE COMMISSION_PCT IS NOT NULL;
END;
/